config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root 'events#index', as: :authenticated_root
    end
  end

  devise_for :users,
             controllers: { omniauth_callbacks: 'user/omniauth_callbacks' },
             only: [:sessions, :omniauth_callbacks]

  resources :events do
    resources :items, only: [:new, :create]
    resources :guests, only: [:new, :create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :items

  validates :title, :description, :start_time, presence: true
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
end

app/models/facebooker.rb
class Facebooker
  attr_accessor :oauth

  def initialize(attrs)
    @oauth = attrs[:oauth]
  end

  def user_exists?
    user.present?
  end

  def user
    User.find_by(uid: @oauth[:uid])
  end

  def register!
    User.create!(
      name: @oauth[:info][:name],
      email: @oauth[:info][:email],
      uid: @oauth[:uid],
      password: SecureRandom.uuid
    )
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable, :omniauthable,
         :rememberable, :validatable
  validates :password, presence: false

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :format_start_time, only: [:create]

  def index
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
    @event.items.build
  end

  def update
    event_params[:items_attributes].each do |_, new_item|
      if new_item[:id] && Item.find(new_item[:id])
        Item.find(new_item[:id]).update(new_item)
      else
        Item.create(new_item.merge(event_id: params[:id]))
      end
    end
    redirect_to event_path(params[:id])
  end

  def new
  end

  def create
    event = Event.create(event_params)
    if event.persisted?
      redirect_to event_path(event)
      return
    end
    render action: :new, event: event
  end

  private

  def format_start_time
    a = params[:event]
    params[:event][:start_time] =
      Time.new(
        a['start_time(1i)'],
        a['start_time(2i)'],
        a['start_time(3i)'],
        a['start_time(4i)'],
        a['start_time(5i)']
      )
  end

  def event_params
    params.require(:event).permit(
      :user_id,
      :title,
      :start_time,
      :description,
      :time,
      items_attributes: [:id, :title, :description, :quantity]
    )
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @event.items.build
  end

  def create
    event_params[:items_attributes].each do |_, new_item|
      if new_item[:id] && Item.find(new_item[:id])
        Item.find(new_item[:id]).update(new_item)
      else
        Item.create(new_item.merge(event_id: params[:event_id]))
      end
    end
    redirect_to event_path(params[:event_id])
  end

  private

  def event_params
    params.require(:event).permit(
      :user_id,
      :title,
      :time,
      items_attributes: [:id, :title, :description, :quantity]
    )
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    fb = Facebooker.new(oauth: request.env['omniauth.auth'])
    fb.register! unless fb.user_exists?
    sign_in(fb.user)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for :event, url: events_path, validate: true do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Título' %><br>
  <%= f.input :description, as: :text, label: 'Descrição do evento', input_html: { rows: 20 } %><br>
  <%= f.input :start_time, as: :datetime, order: [:day, :month, :year, :hour, :minute], label: 'Data/hora de início do Evento' %><br>
  <div class="row button-holder">
    <div class="col-xs-2">
      <%= button_tag type: 'submit', class: 'btn btn-round btn-success' do %>
        <%= fa_icon 'check 4x' %>
      <% end %>
    </div>

    <div class="col-xs-2">
      <%= link_to authenticated_root_path, class: 'btn btn-round btn-danger' do %>
        <%= fa_icon 'remove 4x', style: 'margin-top: 12px;' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= simple_form_for @event, validate: true do |f| %>
  <%= f.error_notification %>
  <div class="btn">
    <%= link_to_add_association f, :items, class: 'btn btn-round btn-left-top btn-primary' do %>
      <%= fa_icon 'plus 4x', style: 'margin-top: 12px;' %>
    <% end %>
  </div>

  <%= f.simple_fields_for :items do |i| %>
    <%= render partial: 'item_fields', locals: { f: i } %>
  <% end %>

  <div class="row button-holder">
    <div class="col-xs-2">
    </div>

    <div class="col-xs-2">
      <%= button_tag type: 'submit', class: 'btn btn-round btn-success' do %>
        <%= fa_icon 'check 4x' %>
      <% end %>
    </div>

    <div class="col-xs-2">
      <%= link_to event_path(@event), class: 'btn btn-round btn-danger' do %>
        <%= fa_icon 'remove 4x', style: 'margin-top: 12px;' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-xs-10"><h1>Eventos</h1></div>
  <div class="col-xs-2">
    <%= link_to new_event_path, class: 'btn btn-block btn-huge btn-primary' do %>
      <%= fa_icon 'plus 2x' %>
    <% end %>
  </div>
</div>
<% if current_user.events.blank? %>
  <h1>Você ainda não tem eventos. Crie o primeiro clicando em "Novo evento"</h1>
<% else %>
  <% current_user.events.each do |event| %>
    <div class="row">
      <div class="col-xs-8 events-list-item">
        <%= link_to event.title, event_path(event) %>
      </div>
      <div class="col-xs-4 events-list-item" align="right">
        <%= event.start_time.strftime('%d/%m/%y %H:%M') %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>Novo evento</h1>
<%= render partial: 'form' %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p class="event-description"><%= @event.description %></p>
<p class="event-description">Começa <%= @event.start_time.strftime('%d/%m/%y %H:%M') %></p>
<% @event.items.each do |item| %>
  <%= item.title %><br>
  <%= item.quantity %>
  <% unless item == @event.items.last %>
    <hr>
  <% end %>
<% end %>
<%= link_to new_event_item_path(@event.id), class: 'btn btn-huge btn-primary' do %>
  <%= fa_icon 'plus 4x' %> lista
<% end %>

app/views/home/index.html.erb
<div align="center"><h1>Girafinea</h1></div>

app/views/items/_item_fields.html.erb
<div class="row">
  <div class="col-xs-10">
    <%= f.input :title, label: 'Item' %>
  </div>
  <div class="col-xs-2">
    <%= f.input :quantity, label: 'Quantidade', as: :integer, input_html: { min: 0 } %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= f.input :description, label: 'Descrição', as: :text, input_html: { rows: 5 } %>
  </div>
</div>

app/views/items/new.html.erb
<%= simple_form_for @event, url: event_items_path, method: :post, validate: true do |f| %>
  <%= f.error_notification %>
  <div class="btn">
    <%= link_to_add_association f, :items, class: 'btn btn-round btn-left-top btn-primary' do %>
      <%= fa_icon 'plus 4x', style: 'margin-top: 12px;' %>
    <% end %>
  </div>

  <%= f.simple_fields_for :items do |i| %>
    <%= render partial: 'item_fields', locals: { f: i } %>
  <% end %>

  <div class="row button-holder">
    <div class="col-xs-2">
    </div>

    <div class="col-xs-2">
      <%= button_tag type: 'submit', class: 'btn btn-round btn-success' do %>
        <%= fa_icon 'check 4x' %>
      <% end %>
    </div>

    <div class="col-xs-2">
      <%= link_to event_path(@event), class: 'btn btn-round btn-danger' do %>
        <%= fa_icon 'remove 4x', style: 'margin-top: 12px;' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Girafínea</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="banner">
      <div class="container">
        <div class="row">
          <div class="col-xs-4 col-md-2 site-logo">
            <%= link_to unauthenticated_root_path do %>
              <%= image_tag('girafinea.png', class: 'site-logo') %>
            <% end %>
          </div>
          <div class="col-xs-offset-4 col-xs-4 col-md-offset-8 col-md-2">
            <% if user_signed_in? %>
              <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-block btn-huge btn-danger vcenter' %>
            <% else %>
              <%= link_to 'Entrar', unauthenticated_root_path, class: 'btn btn-block btn-huge btn-success vcenter' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="content">
      <div name="top-ref"></div>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-mobile hidden-md hidden-lg"><%= value %>
          <a href="javascript:void(0)" class="close-flash-message">X</a>
        </div>
        <div class="alert alert-<%= key %> hidden-xs hidden-sm"><%= value %>
          <a href="javascript:void(0)" class="close-flash-message">X</a>
        </div>
      <% end %>

      <div class="container page-body">
        <%= yield %>
      </div>
      <a href="#top-ref">
        <div class="btn-round btn-right-bottom">
          <div class="btn-up">
            <%= fa_icon 'arrow-up 4x' %>
          </div>
        </div>
      </a>
      <div class="footer">
      </div>
    </div>
  </body>
</html>